export const SEGMENTS = {
  ecommerce: {
    label: 'E-commerce / Marketplace',
    icon: 'ShoppingCart',
    description: 'Loja em Shopee, Mercado Livre, Amazon, Shopify',
    terminologia: {
      pedido: 'Pedido',
      cliente: 'Comprador',
      produto: 'Produto',
      receita: 'Faturamento',
      loja: 'Loja',
    },
    modulosPadrao: [
      'pedidos',
      'estoque',
      'compras',
      'clientes',
      'devolucoes',
      'importar',
      'financeiro',
      'dre',
      'despesas',
      'fluxo_caixa',
      'contas_pagar',
      'analise',
      'curva_abc',
      'comparativo',
      'sazonalidade',
      'alertas',
      'campanhas',
      'ads',
      'calculadora',
      'precificacao',
      'tarefas',
      'reposicao',
      'relatorio',
      'exportar',
    ],
  },
  varejo: {
    label: 'Varejo Físico',
    icon: 'Store',
    description: 'Loja física, ponto de venda, PDV',
    terminologia: {
      pedido: 'Venda',
      cliente: 'Cliente',
      produto: 'Produto',
      receita: 'Faturamento',
      loja: 'Unidade',
    },
    modulosPadrao: [
      'pedidos',
      'estoque',
      'compras',
      'clientes',
      'financeiro',
      'despesas',
      'fluxo_caixa',
      'contas_pagar',
      'analise',
      'comparativo',
      'alertas',
      'calculadora',
      'tarefas',
      'fornecedores',
      'exportar',
    ],
  },
  atacado: {
    label: 'Atacado / Distribuição',
    icon: 'Truck',
    description: 'Distribuidora, representante comercial',
    terminologia: {
      pedido: 'Pedido',
      cliente: 'Cliente',
      produto: 'Item',
      receita: 'Faturamento',
      loja: 'Filial',
    },
    modulosPadrao: [
      'pedidos',
      'estoque',
      'compras',
      'clientes',
      'financeiro',
      'despesas',
      'fluxo_caixa',
      'contas_pagar',
      'break_even',
      'analise',
      'comparativo',
      'alertas',
      'calculadora',
      'tarefas',
      'fornecedores',
      'exportar',
    ],
  },
  servicos: {
    label: 'Prestação de Serviços',
    icon: 'Wrench',
    description: 'Assistência técnica, oficina, consultoria',
    terminologia: {
      pedido: 'OS',
      cliente: 'Cliente',
      produto: 'Serviço',
      receita: 'Receita',
      loja: 'Unidade',
    },
    modulosPadrao: [
      'ordens_servico',
      'clientes',
      'estoque',
      'financeiro',
      'despesas',
      'fluxo_caixa',
      'contas_pagar',
      'analise',
      'alertas',
      'calculadora',
      'tarefas',
      'fornecedores',
      'exportar',
    ],
  },
  industria: {
    label: 'Indústria / Manufatura',
    icon: 'Factory',
    description: 'Produção, manufatura, transformação',
    terminologia: {
      pedido: 'Ordem de Produção',
      cliente: 'Cliente',
      produto: 'Produto',
      receita: 'Faturamento',
      loja: 'Planta',
    },
    modulosPadrao: [
      'pedidos',
      'estoque',
      'compras',
      'clientes',
      'financeiro',
      'dre',
      'despesas',
      'fluxo_caixa',
      'break_even',
      'analise',
      'comparativo',
      'alertas',
      'calculadora',
      'tarefas',
      'fornecedores',
      'exportar',
    ],
  },
} as const;

export type SegmentKey = keyof typeof SEGMENTS;

export type Terminologia = {
  pedido: string;
  cliente: string;
  produto: string;
  receita: string;
  loja: string;
};
